name: vkitti2
data_root: /data/public/vkitti2
split_train: /workspace/Marigold/data_split/vkitti_depth/vkitti_train.txt
dataset_type: vkitti2
radar_simulation: augmented
num_radar_points_min: 30
num_radar_points_max: 60
depth_noise_std: 0.5
train_resize_hw: [480, 640]
batch_size: 12
num_workers: 4
max_radar_points: 128
max_depth: 80.0
min_depth: 1.0e-3
train_crop_hw: null
