#!/usr/bin/env python3
"""Generate day/night sub-splits for nuScenes from `night_ids.txt`.

`night_ids.txt` (one sample_id per line) is the single source of truth for
which samples are night-time. It is generated by either:
  - `scripts/classify_night_clip.py`  (recommended; handles test set too)
  - this script's --from-scene-json mode (keyword search over scene
    descriptions; only works for trainval since test descriptions are masked)

Outputs (under `<splits-dir>/`):
    night_ids.txt            ← only (re)written if --from-scene-json is used
    train_day.txt            ← train.txt rows whose sample_id is NOT in night_ids
    train_night.txt
    val_day.txt
    val_night.txt
    test_day.txt             ← only meaningful if night_ids.txt was generated
    test_night.txt              by classify_night_clip.py (test descriptions are
                                masked, so --from-scene-json yields empty for test)

Usage:
    # 1) After running classify_night_clip.py:
    python scripts/make_splits.py

    # 2) Or to (re)generate night_ids.txt from scene.json descriptions only:
    python scripts/make_splits.py --from-scene-json
"""
import argparse
import json
import logging
import os
import sys

logger = logging.getLogger("make_splits")
logging.basicConfig(format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
                    level=logging.INFO)


def write_lines(path: str, lines):
    with open(path, "w") as f:
        f.write("\n".join(lines) + ("\n" if lines else ""))
    logger.info("wrote %d lines → %s", len(lines), path)


def split_by_night_ids(split_path: str, night_ids: set):
    if not os.path.exists(split_path):
        logger.warning("missing %s — skipping", split_path)
        return None, None
    day, night = [], []
    with open(split_path) as f:
        for line in f:
            line_s = line.rstrip("\n")
            if not line_s.strip():
                continue
            sid = line_s.split("\t", 1)[0]
            (night if sid in night_ids else day).append(line_s)
    return day, night


def regenerate_night_ids_from_scene_json(splits_dir, meta_dirs):
    """Fall-back path: build night_ids.txt by keyword-matching scene.json
    descriptions against split sample_ids via cam_filename → official scene
    name lookup. Equivalent to running classify_night_clip.py with
    threshold=∞ on description text only — works for trainval, not test.
    """
    # Build cam_filename → scene_name mapping (split-local numbering ≠ official).
    fname_to_scene_name = {}
    night_scenes = set()
    for d in meta_dirs:
        sample_p = os.path.join(d, "sample.json")
        sd_p = os.path.join(d, "sample_data.json")
        scene_p = os.path.join(d, "scene.json")
        if not all(os.path.exists(p) for p in (sample_p, sd_p, scene_p)):
            continue
        with open(sample_p) as f:
            sample_to_scene_tok = {s["token"]: s["scene_token"] for s in json.load(f)}
        with open(scene_p) as f:
            scenes = json.load(f)
        scene_tok_to_name = {s["token"]: s["name"] for s in scenes}
        for s in scenes:
            if "night" in (s.get("description") or "").lower():
                night_scenes.add(s["name"])
        with open(sd_p) as f:
            for sd in json.load(f):
                fn = os.path.basename(sd["filename"]).rsplit(".", 1)[0]
                tok = sample_to_scene_tok.get(sd["sample_token"])
                if tok:
                    fname_to_scene_name[fn] = scene_tok_to_name[tok]
    logger.info(f"night scenes from scene.json descriptions: {len(night_scenes)}")

    night_ids = []
    for split in ("train", "val", "test"):
        sp = os.path.join(splits_dir, f"{split}.txt")
        if not os.path.exists(sp):
            continue
        with open(sp) as f:
            for line in f:
                sid = line.split("\t", 1)[0].strip()
                fname = sid.split("/", 1)[1] if "/" in sid else sid
                official = fname_to_scene_name.get(fname)
                if official in night_scenes:
                    night_ids.append(sid)
    write_lines(os.path.join(splits_dir, "night_ids.txt"), night_ids)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--splits-dir", default="/data/public/nuScenes/derived/splits")
    parser.add_argument("--meta-dirs", nargs="+", default=[
        "/data/public/nuScenes/trainval/v1.0-trainval",
        "/data/public/nuScenes/test/v1.0-test",
    ])
    parser.add_argument("--from-scene-json", action="store_true",
                        help="(re)generate night_ids.txt from scene.json descriptions only "
                             "(trainval coverage, no test set)")
    args = parser.parse_args()

    if not os.path.isdir(args.splits_dir):
        logger.error("splits dir does not exist: %s", args.splits_dir)
        sys.exit(2)

    if args.from_scene_json:
        regenerate_night_ids_from_scene_json(args.splits_dir, args.meta_dirs)

    night_ids_path = os.path.join(args.splits_dir, "night_ids.txt")
    if not os.path.exists(night_ids_path):
        logger.error("night_ids.txt not found at %s; run classify_night_clip.py "
                     "or pass --from-scene-json first.", night_ids_path)
        sys.exit(2)
    with open(night_ids_path) as f:
        night_ids = {ln.strip() for ln in f if ln.strip()}
    logger.info(f"loaded {len(night_ids)} night sample_ids from {night_ids_path}")

    for split in ("train", "val", "test"):
        sp = os.path.join(args.splits_dir, f"{split}.txt")
        day, night = split_by_night_ids(sp, night_ids)
        if day is None:
            continue
        write_lines(os.path.join(args.splits_dir, f"{split}_day.txt"), day)
        write_lines(os.path.join(args.splits_dir, f"{split}_night.txt"), night)

    logger.info("done.")


if __name__ == "__main__":
    main()
